email_receiver: {
    Bob:{
        receiver: jbsv43@sina.com,
        cc:
    },
}

report: {
    access_address:  ,    
    version: v1.0,
    ui_test: 1,
    app_test: 0,
    win_test: 1,
}

env: {
    QA: {
        user: {
            account: jbsv43,
        },
    },
}