email_sender: {
    smtp_server: smtp.qiye.aliyun.com,
    sender: automation@byincd.com,
    sender_username: automation@byincd.com,
    sender_password:
}

rerun: {
    rerun_times: 3,
    rerun_delay: 5,
}