email_sender: {
    smtp_server: smtp.qiye.aliyun.com,
    sender: automation@byincd.com,
    sender_username: automation@byincd.com,
    sender_password: pwd,
    send_report: false
}

rerun: {
    rerun_times: 1,
    rerun_delay: 2,
}

webdriver: {
    timeout: 30
}

video: {
    record: false,
    time_limit: 10
}