email_sender: {
    smtp_server: smtp.qiye.aliyun.com,
    sender: automation@byincd.com,
    sender_username: automation@byincd.com,
    sender_password: pwd,
    send_report: false
}

storage: {
    dbname: automation_history,
    port: 3306,
    charset: utf8
}

rerun: {
    rerun_times: 1,
    rerun_delay: 2,
}

webdriver: {
    timeout: 30
}

video: {
    record: false,
    only_record_failed: true
}