email_receiver: {
    Bob:{
        receiver: jbsv43@sina.com,
        cc:
    },
}

report: {
    access_address:  ,    
    version: v1.0,
    ui_test: 0,
    app_test: 0,
    win_test: 0,
}

env: {
    QA: {
        base_url: "https://jsonplaceholder.typicode.com",
        api_list: {
            posts: posts,
            post_comment: posts/<param>/comments
        }
    },
}